version: "3.4"
services:
  security-cam:
    build: .
    container_name: security-cam
    hostname: security-cam
    restart: unless-stopped
    devices:
      - /dev/video0
      - /dev/vchiq
    volumes:
      - /opt/vc:/opt/vc
    network_mode: host
    environment:
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
      - STREAM_FPS=30
      - HUB_REST_ENDPOINT=http://192.168.50.166:8080
      - THRESHOLD=100
